apiVersion: batch/v1
kind: Job
metadata:
  name: tf-check
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: tf-validate
          image: hashicorp/terraform:1.7
          workingDir: /workspace/terraform
          command: ["sh", "-c", "terraform init && terraform validate"]
          volumeMounts:
            - name: repo
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: repo
          hostPath:
            path: /home/runner/work/GithubProjects-VM-/GithubProjects-VM-
  backoffLimit: 2
