apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
    - name: demo
      image: busybox
      command: ["sh", "-c", "echo $APP_MODE $GREETING && sleep 3600"]
      envFrom:
        - configMapRef:
            name: app-config
