name: Demo
on:
  workflow_dispatch:
env:
  Global_Var: "This is a global variable"
jobs:
  say_hello_in_bash:
    runs-on: ubuntu-latest
    env:
      JOb_var: "This is a job variable"
    steps:
      - name: Hello world in bash
        run: |
          echo "Hello world from bash"
          echo "whoami"
          echo "pwd"
          echo "ls"
          echo "ls -al"
          echo "date"
          echo "Global Variable: ${{ env.Global_Var }}"
          echo "Job Variable: ${{ env.JOb_var }}"
  say_hello_in_c:
    runs-on: windows-latest
    env:
      JOb_var: "This is a job variable"
    steps:
      - name: Hello world in c
        env:
          step_var: "This is a step variable"
        run: |
          echo "Hello world from c"
          echo "whoami"
          echo "pwd"
          echo "ls"
          echo "ls -al"
          echo "date"
          echo "Step Variable: ${{ env.step_var }}"
          echo "Global Variable: ${{ env.Global_Var }}"
          echo "Job Variable: ${{ env.JOb_var }}"
  say_hello_in_python:
    runs-on: macos-latest
    steps:
      - name: Hello world in python
        run: |
          echo "Hello world from python"
          echo "whoami"
          echo "pwd"
          echo "ls"
          echo "ls -al"
          echo "date"
  todays_report:
    runs-on: ubuntu-latest
    needs:
      - say_hello_in_bash
    steps:
      - name: todays_report
        run: |
          echo " Date: $(date)"
          echo " Time: $(date +%T)"
          echo " User: $(whoami)"
          echo " Current Directory: $(pwd)"
          echo " Files in Current Directory: $(ls)"
          echo "Current Process: $(ps)"
          echo "Thank you for using our service!"
  version:
    runs-on: ubuntu-latest
    steps:
      - name: version
        id: ver
        run: |
          echo "Version=$(date +%Y.%m.%d.%H.%M.%S)" >> $GITHUB_OUTPUT
      - name: Print version
        run: |
          echo "Version: ${{ steps.ver.outputs.Version }}"